# Single Layer Perceptron Learning Algorithm ( less train data)

In [1]:
#importing necessary pakaga
import numpy as np

In [2]:
# initialize weight matrix and treshold, present input X, and desired output d

def init(bits):
    n = 2**bits                             # number of inputs = 2^bits
    
    w = np.random.uniform(0,1,(1,bits+1))   # initializing weight matrix w, adding threshold as bias to 0th element w[0][0]
    w[0][0] = -0.5
    
    # preparing the inputs and desired outputs
    test_x = np.zeros((bits+1,n))
    train_x = np.zeros((bits+1,n//2))
    
    ## test data prepare
    for i in range(0,n):
        test_x[0][i]=1
        for j in range(0,bits):
            if(i&(1<<j)):
                test_x[j+1][i]=1
    
    ## train data prepare
    for i in range(0,n):
        if(i%2==0):
            train_x[:,i//2]=test_x[:,i]
    
    ## train desired output
    d = np.zeros((1,n//2))
    for i in range(n//4,n//2):
        d[0][i]=1
    
    ## test desired ouput
    test_y = np.zeros((1,n))
    for i in range(n//2,n):
        test_y[0][i]=1
        
    return n,w,train_x,d,test_x,test_y

In [3]:
### step function
def f_h(n):
    if(n>=0):
        return 1
    else:
        return 0

In [4]:
def learn_widrow_hoff_with_group(n,w,x,d,bits):
    """
    parameter:
        n = number of inputs  = 2^bits
        w = initial weight matrix with bias, shape of (1,bits+1)
        x = inputs , shape of (bits+1,n)
        d = desired output , shape of (1,n)
        bits = number of bits to train
    return:
        w = resultant weight matrix, shape of (1,bits+1)
    """
    flag = 1
    gain = 0.6
    st = 0
    mid = n//2
    while(flag):
        flag=0
        for i in range (st,n):
            y = f_h(np.matmul(w,x[:,i]))
            delta = d[0][i]-y                             # delta = d(t)-y(t)
            if(delta!=0):   
                w[0,1:] = w[0,1:]+gain*delta*x[1:,i]
                if(i<mid):                                # if not equal in 1st class
                    st=0                                  # goto 1st class top
                else:
                    st=mid                                # else goto 2nd class top
                flag=1
                break
        if(flag==0 and st!=0):                            # for checking all the inputs are checked
            flag=1
            st=0
    return w

In [10]:
bits = int(input('Enter number of bits: '))

n,w,train_x,d,test_x,test_y = init(bits)
print(n)
print('training data = '+ str(n//2))
print(w)
print(train_x)
print(d) 

w = learn_widrow_hoff_with_group(n//2,w,train_x,d,bits)
print("ok")
print(w)

Enter number of bits: 20
1048576
training data = 524288
[[-0.5         0.80973904  0.38886522  0.59025897  0.58630036  0.22337186
   0.6946773   0.3928069   0.16762739  0.64104744  0.15806476  0.04312513
   0.54447961  0.91553553  0.30767796  0.43950314  0.66846285  0.56414776
   0.973011    0.99322605  0.40384264]]
[[1. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
[[0. 0. 0. ... 1. 1. 1.]]
ok
[[-0.5         0.80973904 -0.21113478 -0.00974103 -0.01369964 -0.37662814
  -0.5053227  -0.2071931  -0.43237261  0.04104744 -0.44193524  0.04312513
  -0.05552039 -0.28446447  0.30767796 -0.16049686  0.06846285 -0.03585224
  -0.226989   -0.20677395  4.60384264]]


In [11]:
### saving the weight
np.savetxt('w1.csv', w, delimiter=',')

In [12]:
### reading weight from file
W = np.loadtxt('w1.csv', delimiter = ',')

In [13]:
y = np.matmul(W,test_x)
print(y)
print('total test data = ' + str(n))

cnt=0;

for i in range(0,n):
        cnt+=abs(test_y[0][i]-f_h(y[i]))
print('total misclassified data = ' + str(cnt))
print('Accuracy =' + str(100*(n-cnt)/n) + '%')

[-0.5         0.30973904 -0.71113478 ...  2.41690568  1.39603187
  2.2057709 ]
total test data = 1048576
total misclassified data = 6796.0
Accuracy =99.35188293457031%
