# Single Layer Perceptron Learning Algorithm

Here we have only one artificial neuron by which we classify inputs into two classes: 0 or 1

<img src = "single neuron.png">

## Input description
bits = number of bits we want to train
<br>X2, X1 are input bits, b is the bias

## Output Description
weights matrix and threshold value, number of weights equal to the number of bits (input) and we also include the threshold value to the weight matrix as bias

In [1]:
# importing necessary pakaga
import numpy as np

In [2]:
# initialize weight matrix and treshold, present input X, and desired output d

def init(bits):
    n = 2**bits                             # number of inputs = 2^bits
    
    w = np.random.uniform(0,1,(1,bits+1))   # initializing weight matrix w, adding threshold as bias to 0th element w[0][0]
    w[0][0] = -0.5
    
    # preparing the inputs and desired outputs
    x = np.zeros((bits+1,n))
    for i in range(0,n):
        x[0][i]=1
        for j in range(0,bits):
            if(i&(1<<j)):
                x[j+1][i]=1
    
    d = np.zeros((1,n))
    for i in range(n//2,n):
        d[0][i]=1
        
    return n,w,x,d

In [3]:
### step function
def f_h(n):
    if(n>=0):
        return 1
    else:
        return 0

In [4]:
def learn(n,w,x,d,bits):
    """
    parameter:
        n = number of inputs  = 2^bits
        w = initial weight matrix with bias, shape of (1,bits+1)
        x = inputs , shape of (bits+1,n)
        d = desired output , shape of (1,n)
        bits = number of bits to train
    return:
        w = resultant weight matrix, shape of (1,bits+1)
    """
    flag = 1 
    while(flag):
        flag=0
        for i in range (0,n):
            y = f_h(np.matmul(w,x[:,i]))
            if(y<d[0][i]):                      # output is 0, should be 1
                w[0,1:] = w[0,1:]+x[1:,i]
                flag=1
                break
            elif(y>d[0][i]):                    #output is 1, should be 0
                w[0,1:] = w[0,1:]-x[1:,i]
                flag=1
                break
    
    return w

In [5]:
def learn_widrow_hoff(n,w,x,d,bits):
    flag = 1
    gain = 0.6                                # gain term for better convergence
    
    while(flag):
        flag=0
        for i in range (0,n):
            y = f_h(np.matmul(w,x[:,i]))
            delta = d[0][i]-y                 # delta = d(t)-y(t)
            if(delta!=0):   
                w[0,1:] = w[0,1:]+gain*delta*x[1:,i]
                flag=1
                break
    return w

In [6]:
def learn_widrow_hoff_with_group(n,w,x,d,bits):
    flag = 1
    gain = 0.6
    st = 0
    mid = n//2
    while(flag):
        flag=0
        for i in range (st,n):
            y = f_h(np.matmul(w,x[:,i]))
            delta = d[0][i]-y                             # delta = d(t)-y(t)
            if(delta!=0):   
                w[0,1:] = w[0,1:]+gain*delta*x[1:,i]
                if(i<mid):                                # if not equal in 1st class
                    st=0                                  # goto 1st class top
                else:
                    st=mid                                # else goto 2nd class top
                flag=1
                break
        if(flag==0 and st!=0):                            # for checking all the inputs are checked
            flag=1
            st=0
    return w

In [7]:
bits = int(input('Enter number of bits: '))

n,w,x,d = init(bits)
#print(n)
#print(w)
print(x)
#print(d) 

#w = learn(n,w,x,d,bit)
#w = learn_widrow_hoff(n,w,x,d,bit)
w = learn_widrow_hoff_with_group(n,w,x,d,bits)
print("ok")
print(w)

Enter number of bits: 16
[[1. 1. 1. ... 1. 1. 1.]
 [0. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 1. 1.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 1. 1. 1.]]
ok
[[-0.5        -0.41442169 -0.44792418  0.04313304 -0.09868416 -0.33953938
  -0.19967623 -0.31988311  0.09216644 -0.22907402 -0.24095503 -0.41594061
  -0.11216565 -0.07703619 -0.29081806 -0.20177142  4.22947227]]


In [8]:
### saving the weight
np.savetxt('w.csv', w, delimiter=',')

In [9]:
### reading weight from file
W = np.loadtxt('w.csv', delimiter = ',')

In [10]:
test = np.zeros((bits+1,1))
test[0][0]=1
k=1
while(k!=-1):
    for i in range(1,bits+1):
        k = int(input('Enter ' +str(i)+' bit: '))
        if(k==-1):
            break
        test[i][0]=k

    y = f_h(np.matmul(W,test))
    print(y)

Enter 1 bit: 0
Enter 2 bit: 0
Enter 3 bit: 0
Enter 4 bit: 0
Enter 5 bit: 0
Enter 6 bit: 0
Enter 7 bit: 0
Enter 8 bit: 0
Enter 9 bit: 0
Enter 10 bit: 0
Enter 11 bit: 1
Enter 12 bit: 0
Enter 13 bit: 0
Enter 14 bit: 0
Enter 15 bit: 0
Enter 16 bit: 0
0
Enter 1 bit: -1
0


In [ ]:
i = int(input('Enter: '))
while(i!=-1):
    y = f_h(np.matmul(W,x[:,i]))
    print(y)
    i = int(input('Enter: '))



In [24]:
y = np.matmul(W,x)
print(y)

cnt=0;

for i in y:
    if(i>=0):
        cnt+=1
print(cnt)


[-0.5        -0.70688532 -0.85618681 ...  1.27294532  1.12364382
  0.9167585 ]
512


In [11]:
np.savetxt('x.csv', x, delimiter=',')
np.savetxt('d.csv', d, delimiter=',')