# Multilayer perceptron using backpropagation algorithm

In [1]:
import numpy as np
# SKLEARN
from sklearn.utils import shuffle
from sklearn.cross_validation import train_test_split

/home/mirror/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
## initialize variable

def init(li, lh, lo):
    w1 = np.random.uniform(0,1,(li,lh))    #(input, hidden)
    w2 = np.random.uniform(0,1,(lh,lo))    #(hidden, output)
    th1 = np.random.uniform(0,1,(lh,1))    #(hidden, 1)
    th2 = np.random.uniform(0,1,(lo,1))    #(output, 1)
    
    k1 = 0.5
    k2 = 0.6
    
    n = 1<<li      #(2^li)
    lim = n//lo    #number in one class
    
    train_x = np.zeros((n,li))   # (2^input, input)
    train_y = np.zeros((n,lo))   # (2^input, output)
    
    for i in range(0,n):
        for j in range(0,li):
            if(i&(1<<j)):
                train_x[i][j]=1
    for i in range(0,n):
        train_y[i,i//lim]= 1
    
    return n, train_x, train_y, w1, w2, th1, th2, k1, k2

In [3]:
def sigmoid(k, activ):
    t = 1 + np.exp(-1*k*activ)
    return (1/t)

In [4]:
def layer(x,w,th,k):
    net = np.matmul(x,w)
    activ = net + np.transpose(th)
    out = sigmoid(k,activ)
    return out

In [5]:
def calculate_tot_error(train_x, train_y, w1, w2, th1, th2, k1, k2):
    oj = layer(train_x, w1, th1, k1)
    ok = layer(oj, w2, th2, k1)
    t = np.sum((train_y - ok)**2)*0.5
    return t

In [6]:
def learn_multilayer(n, li, lh, lo, train_x, train_y, w1, w2, th1, th2, k1, k2):
    """
    parameter:
        train_x = inputs , shape of (n,li)
        train_y = desired output , shape of (n,lo)
        w1 = weight of input layer, shape of (li,lh)
        w2 = weight of hidden layer, shape of (lh,lo)
        th1 = threshold of input layer, shape of (lh,1)
        th2 = threshole of hidden layer , shape of (lo,1)
        k1, k2  = 
    return:
        w1, w2, th1, th2
    """
    learning_rate1 = 0.01
    learning_rate2 = 0.01
    cnt=0
    
    while(True):
        for i in range (0,n):
            
            Oj = layer(np.reshape(train_x[i,:],(1,li)), w1, th1, k1)
            
            Ok = layer(Oj, w2, th2, k2)
            
            
            err = train_y[i,:] - Ok      # (1,lo)
            
            
            del_w2 = np.matmul(np.transpose(Oj),learning_rate2*k2*err*Ok*(1-Ok))
            w2 = w2 + del_w2

            del_th2 = learning_rate2*k2*err*Ok*(1-Ok)
            th2 = th2 + np.transpose(del_th2)


            s = np.matmul(err, np.transpose(w2))
            s = learning_rate1*k1*Oj*(1-Oj)*s

            del_w1 = np.matmul(np.transpose(np.reshape(train_x[i,:],(1,li))), s)
            w1 = w1 + del_w1

            del_th1 = np.transpose(s)
            th1 = th1 + del_th1
            
        totalError = calculate_tot_error(train_x, train_y, w1, w2, th1, th2, k1, k2)
        cnt+=1
        
        if(cnt%1000 ==0 ):
            print(totalError)
        if(totalError<0.01 or cnt==1000000):
            break
                
                
    return w1, w2, th1, th2

In [8]:
n, x, y, w1, w2, th1, th2, k1, k2 = init(6,3,4)

train_x, test_x, train_y, test_y = train_test_split(x,y, test_size = 0.2)

print(train_x)
print(train_y)
print(w1)
print(w2)
print(th1)
print(th2)
n = train_x.shape[0]
w1, w2, th1, th2 = learn_multilayer(n, 6, 3, 4, train_x, train_y, w1, w2, th1, th2, k1, k2)

print('-------')
print(w1)
print(w2)
print(th1)
print(th2)

[[1. 0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0.]
 [1. 1. 1. 0. 0. 1.]
 [0. 0. 1. 1. 1. 0.]
 [1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 1.]
 [1. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 1. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 1.]
 [1. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1.]
 [0. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 0. 0.]
 [1. 1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0.

0.03245530837195456
0.03236225541037263
0.03226978646745319
0.032177895902254144
0.032086578147247885
0.031995827707140344
0.0319056391576885
0.031816007144540775
0.031726926382108715
0.031638391652459755
0.03155039780422694
0.031462939751541893
0.03137601247298487
0.03128961101056613
0.031203730468720044
0.031118366013308703
0.03103351287066389
0.030949166326625376
0.030865321725623816
0.03078197446975922
0.030699120017894464
0.030616753884775978
0.0305348716401821
0.030453468908072084
0.03037254136574692
0.030292084743040876
0.030212094821504387
0.030132567433635522
0.030053498462095714
0.029974883838973093
0.029896719544986357
0.029819001608790193
0.029741726106250452
0.029664889159753776
0.02958848693749622
0.029512515652807287
0.029436971563483676
0.02936185097113451
0.029287150220534047
0.029212865698988205
0.02913899383571704
0.029065531101242947
0.02899247400677782
0.028919819103647493
0.028847562982708255
0.028775702273779666
0.028704233645079964
0.02863315380268306
0.02856245

0.015782789272540607
0.01576366591498935
0.015744593407548066
0.015725571541638308
0.015706600109842327
0.015687678905889832
0.015668807724651332
0.015649986362132884
0.015631214615461082
0.01561249228287354
0.01559381916371609
0.0155751950584311
0.015556619768561994
0.015538093096734443
0.015519614846653916
0.015501184823100148
0.015482802831916444
0.015464468679992974
0.01544618217527232
0.01542794312673021
0.01540975134438617
0.015391606639286176
0.015373508823494853
0.015355457710093884
0.015337453113177158
0.015319494847826751
0.015301582730120528
0.015283716577117492
0.01526589620685813
0.015248121438360879
0.015230392091607512
0.015212707987540415
0.015195068948061108
0.01517747479601754
0.015159925355190913
0.015142420450299643
0.015124959906982942
0.015107543551808787
0.015090171212262738
0.015072842716736236
0.015055557894527973
0.015038316575837785
0.015021118591758425
0.015003963774259341
0.01498685195619404
0.014969782971283737
0.014952756654121966
0.014935772840169068
0.0

In [24]:
Oj = layer(np.reshape(train_x[62,:], (1,6)), w1, th1, k1)
Ok = layer(Oj, w2, th2, k2)
print(Ok)

[[1.69134325e-05 4.20187819e-03 4.19941898e-03 9.93004820e-01]]


In [10]:
totalError = calculate_tot_error(test_x, test_y, w1, w2, th1, th2, k1, k2)
print((1-totalError)*100)

99.69228944927036
