# Multi Layer perceptron using backpropagation algorithm

In [9]:
import numpy as np

In [10]:
## initialize variable

def init():
    w1 = np.random.uniform(0,1,(2,2))
    w2 = np.random.uniform(0,1,(2,1))
    th1 = np.random.uniform(0,1,(2,1))
    th2 = np.random.uniform(0,1,(1,1))
    
    k1 = 0.6
    k2 = 0.8
    
    train_x = np.zeros((4,2))
    train_y = np.zeros((4,1))
    
    for i in range(0,4):
        for j in range(0,2):
            if(i&(1<<j)):
                train_x[i][j]=1
    
    train_y[1,0] = train_y[2,0]=1
    
    return train_x, train_y, w1, w2, th1, th2, k1, k2

In [11]:
def sigmoid(k, activ):
    t = 1 + np.exp(-1*k*activ)
    return (1/t)

In [12]:
def layer(x,w,th,k):
    net = np.matmul(x,w)
    activ = net + np.transpose(th)
    out = sigmoid(k,activ)
    return out

In [21]:
def calculate_tot_error(train_x, train_y, w1, w2, th1, th2, k1, k2):
    oj = layer(train_x, w1, th1, k1)
    ok = layer(oj, w2, th2, k1)
    t = np.sum((train_y - ok)**2)*0.5
    return t

In [40]:
def learn_multilayer(train_x, train_y, w1, w2, th1, th2, k1, k2):
    """
    parameter:
        train_x = inputs , shape of (4,2)
        train_y = desired output , shape of (4,1)
        w1 = weight of input layer, shape of (2,2)
        w2 = weight of hidden layer, shape of (2,1)
        th1 = threshold of input layer, shape of (2,1)
        th2 = threshole of hidden layer , shape of (1,1)
        k1, k2  = 
    return:
        w1, w2, th1, th2
    """
    learning_rate1 = 0.01
    learning_rate2 = 0.01
    cnt=0
    
    while(True):
        for i in range (0,4):
            #print('-----------')
           # net_j = np.matmul(np.reshape(train_x[i,:],(1,2)),w1)   # (1,2)
            #activ_j = net_j + np.transpose(th1)    # (1,2)
           # O_j = sigmoid(k1, activ_j)             # (1,2)
            
            Oj = layer(np.reshape(train_x[i,:],(1,2)), w1, th1, k1)
            
            
           # net_k = np.matmul(O_j,w2)     # (1,1)
           # activ_k = net_k + th2         # (1,1)
           # O_k = sigmoid(k2, activ_k)    # (1,1)
            
            Ok = layer(Oj, w2, th2, k2)
            
            
            err = train_y[i,0] - Ok      # (1,1)
            
            
            del_w2 = learning_rate2*k2*err*Oj*Ok*(1-Ok)
            w2 = w2 + np.transpose(del_w2)

            del_th2 = learning_rate2*k2*err*Ok*(1-Ok)
            th2 = th2 + del_th2


            s = np.matmul(err, np.transpose(w2))
            s = learning_rate1*k1*Oj*(1-Oj)*s

            del_w1 = np.matmul(np.transpose(np.reshape(train_x[i,:],(1,2))), s)
            w1 = w1 + del_w1

            del_th1 = np.transpose(s)
            th1 = th1 + del_th1
            
        totalError = calculate_tot_error(train_x, train_y, w1, w2, th1, th2, k1, k2)
        cnt+=1
        if(totalError<0.01 or cnt==1000000):
            print(totalError)
            break
                
                
    return w1, w2, th1, th2

In [41]:
train_x, train_y, w1, w2, th1, th2, k1, k2 = init()

print(train_x)
print(train_y)
print(w1)
print(w2)
print(th1)
print(th2)

w1, w2, th1, th2 = learn_multilayer(train_x, train_y, w1, w2, th1, th2, k1, k2)

print('-------')
print(w1)
print(w2)
print(th1)
print(th2)

[[0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 1.]]
[[0.]
 [1.]
 [1.]
 [0.]]
[[0.38290281 0.7572064 ]
 [0.47573091 0.29563531]]
[[0.76521236]
 [0.97995758]]
[[0.76068103]
 [0.74352   ]]
[[0.74609592]]
0.009999995386084492
-------
[[12.57730034 15.44662292]
 [12.57746799 15.44811804]]
[[-9.2307955 ]
 [ 8.81008663]]
[[-19.16758387]
 [ -7.1285499 ]]
[[-4.20755008]]


In [46]:
Oj = layer(np.reshape(train_x[1,:], (1,2)), w1, th1, k1)
Ok = layer(Oj, w2, th2, k2)
print(Ok)

[[0.97055927]]
